:concurrency: 10

production:
  :pidfile: /var/www/wattle/shared/tmp/pids/sidekiq.pid
  :logfile: /var/www/wattle/shared/log/sidekiq.log

:queues:
  - [prod_wat_creation, 50]
  - [high, 5]
  - default
  - mailers
  - searchkick